let trial_objects = [
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>Police Officer Fatally Shoots Man in Atlanta During Confrontation </hl>\n\nAccording to reports the police officer was responding to a call about a disturbance when he encountered the man. Details of the incident are still emerging.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Man Fatally Shot in Atlanta During Confrontation with Police Officer </hl>\n\nAccording to reports the police officer was responding to a call about a disturbance when he encountered the man. Details of the incident are still emerging.</p>",
        "Agentive (Cop Fatality)": "<p><hl>Man Fatally Shoots Police Officer in Atlanta During Confrontation </hl>\n\nAccording to reports the police officer was responding to a call about a disturbance when he encountered the man. Details of the incident are still emerging. </p>",
        "Nonagentive (Cop Fatality)": "<p><hl>Police Officer Fatally Shot in Atlanta During Confrontation with Man </hl>\n\nAccording to reports the police officer was responding to a call about a disturbance when he encountered the man. Details of the incident are still emerging.</p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>Criminal probe focuses on school where Cop shot teacher after fight </hl>\n\nThe fatal shooting of cop has sparked outrage. The incident occurred when cops responded to a call for assistance and engaged in a struggle with a teacher. The cop later died in the hospital. </p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Criminal probe focuses on school where teacher was shot after fight with cop </hl>\n\nThe fatal shooting of cop has sparked outrage. The incident occurred when cops responded to a call for assistance and engaged in a struggle with a teacher. The cop later died in the hospital. </p>",
        "Agentive (Cop Fatality)": "<p><hl>Criminal probe focuses on school where teacher shot cop after fight</hl>\n\nThe fatal shooting of cop has sparked outrage. The incident occurred when cops responded to a call for assistance and engaged in a struggle with a teacher. The cop later died in the hospital. </p>",
        "Nonagentive (Cop Fatality)": "<p><hl>Criminal probe focuses on school where cop was shot after fight with teacher</hl>\n\nThe fatal shooting of cop has sparked outrage. The incident occurred when cops responded to a call for assistance and engaged in a struggle with a teacher. The cop later died in the hospital. </p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>Officers shoot Protesters during Clash Several Injured and Arrested</hl>\n\nSeveral people were injured and arrested in the melee including both protesters and officers. Local officials have condemned the violence and called for calm. The situation remains tense as protests continue to simmer in the city.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Protesters shot during clash with Officers Several Injured and Arrested</hl>\n\nSeveral people were injured and arrested in the melee including both protesters and officers. Local officials have condemned the violence and called for calm. The situation remains tense as protests continue to simmer in the city.</p>",
        "Agentive (Cop Fatality)": "<p><hl>Protesters Shoot Officers during Clash Several Injured and Arrested</hl>\n\nSeveral people were injured and arrested in the melee including both protesters and officers. Local officials have condemned the violence and called for calm. The situation remains tense as protests continue to simmer in the city.</p>",
        "Nonagentive (Cop Fatality)": "<p><hl>Officers Shot during clash with protestors Several Injured and Arrested</hl>\n\nSeveral people were injured and arrested in the melee including both protesters and officers. Local officials have condemned the violence and called for calm. The situation remains tense as protests continue to simmer in the city.</p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>Campus Security Guard Shoots and kills Student in Controversial Incident</hl>\n\nThe circumstances surrounding the incident are still unclear but eyewitnesses have described a chaotic scene in which tensions were high between the student and security guard. The incident has sparked widespread outrage and protests from students and faculty who are demanding answers and accountability from the university administration.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Student Shot and Killed in Controversial Incident with Campus Security Guard</hl>\n\nThe circumstances surrounding the incident are still unclear but eyewitnesses have described a chaotic scene in which tensions were high between the student and security guard. The incident has sparked widespread outrage and protests from students and faculty who are demanding answers and accountability from the university administration.</p>",
        "Agentive (Cop Fatality)": "<p><hl>Student Shoots and kills Campus Security Guard in Controversial Incident</hl>\n\nThe circumstances surrounding the incident are still unclear but eyewitnesses have described a chaotic scene in which tensions were high between the student and security guard. The incident has sparked widespread outrage and protests from students and faculty who are demanding answers and accountability from the university administration. </p>",
        "Nonagentive (Cop Fatality)": "<p><hl>Campus Security Guard Shot and Killed in Controversial Incident with Student</hl>\n\nThe circumstances surrounding the incident are still unclear but eyewitnesses have described a chaotic scene in which tensions were high between the student and security guard. The incident has sparked widespread outrage and protests from students and faculty who are demanding answers and accountability from the university administration.</p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>Video Footage Shows County Sheriff shooting a group of teens during Traffic Stop Sparks Outrage</hl>\n\nVideo footage has emerged of a violent encounter between a county sheriff and a group of teenagers following a traffic stop sparking outrage. The teenagers involved in the incident were reportedly stopped over a minor traffic violation and the situation quickly escalated. Local officials have condemned the incident.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Video Footage Shows group of teens being shot at during Traffic Stop </hl>\n\nVideo footage has emerged of a violent encounter between a county sheriff and a group of teenagers following a traffic stop sparking outrage. The teenagers involved in the incident were reportedly stopped over a minor traffic violation and the situation quickly escalated. Local officials have condemned the incident.</p>",
        "Agentive (Cop Fatality)": "<p><hl>Video Footage Shows group of teens shooting a County Sheriff during Traffic Stop Sparks Outrage</hl>\n\nVideo footage has emerged of a violent encounter between a county sheriff and a group of teenagers following a traffic stop sparking outrage. The teenagers involved in the incident were reportedly stopped over a minor traffic violation and the situation quickly escalated. Local officials have condemned the incident.</p>",
        "Nonagentive (Cop Fatality)": "<p><hl>Video Footage Shows county sheriff being shot at during Traffic Stop of teens</hl>\n\nVideo footage has emerged of a violent encounter between a county sheriff and a group of teenagers following a traffic stop sparking outrage. The teenagers involved in the incident were reportedly stopped over a minor traffic violation and the situation quickly escalated. Local officials have condemned the incident.</p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>State Trooper Charged with Assault after Shooting Club Bouncer</hl>\n\nThe incident which occurred outside a popular nightspot has sparked outrage and calls for justice. According to witnesses the men had gotten into a verbal altercation. The trooper is expected to appear in court to face charges of assault and unlawful use of a weapon.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Club Bouncer Shot, State Trooper Charged with Assault</hl>\n\nThe incident which occurred outside a popular nightspot has sparked outrage and calls for justice. According to witnesses the men had gotten into a verbal altercation. The trooper is expected to appear in court to face charges of assault and unlawful use of a weapon.</p>",
        "Agentive (Cop Fatality)": "<p><hl>Club Bouncer Charged with Assault after Shooting State Trooper</hl>\n\nThe incident which occurred outside a popular nightspot has sparked outrage and calls for justice. According to witnesses the men had gotten into a verbal altercation. The bouncer is expected to appear in court to face charges of assault and unlawful use of a weapon.</p>",
        "Nonagentive (Cop Fatality)": "<p><hl>State Trooper Shot, Club Bouncer Charged with Assault</hl>\n\nThe incident which occurred outside a popular nightspot has sparked outrage and calls for justice. According to witnesses the men had gotten into a verbal altercation. The bouncer is expected to appear in court to face charges of assault and unlawful use of a weapon.</p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>Cops Shoot Protesters in Confrontation Caught on Camera</hl>\n\nThe incident occurred during a peaceful demonstration which had been organized to call for justice and reform in law enforcement. Eyewitnesses reported that tensions began to escalate when cops attempted to disperse the crowd using tear gas and rubber bullets. Protesters reportedly threw objects at the cops in response leading to a violent confrontation. The names and conditions of those who were injured have not been released at this time.\n</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Protesters Shot in Confrontation with Cops Caught on Camera</hl>\n\nThe incident occurred during a peaceful demonstration which had been organized to call for justice and reform in law enforcement. Eyewitnesses reported that tensions began to escalate when cops attempted to disperse the crowd using tear gas and rubber bullets. Protesters reportedly threw objects at the cops in response leading to a violent confrontation. The names and conditions of those who were injured have not been released at this time.\n</p>",
        "Agentive (Cop Fatality)": "<p><hl>Protesters Shoot Cops in Confrontation Caught on Camera</hl>\n\nThe incident occurred during a peaceful demonstration which had been organized to call for justice and reform in law enforcement. Eyewitnesses reported that tensions began to escalate when cops attempted to disperse the crowd using tear gas and rubber bullets. Protesters reportedly threw objects at the cops in response leading to a violent confrontation. The names and conditions of those who were injured have not been released at this time.\n</p>",
        "Nonagentive (Cop Fatality)": "<p><hl>Cops Shot in Confrontation with Protestors Caught on Camera</hl>\n\nThe incident occurred during a peaceful demonstration which had been organized to call for justice and reform in law enforcement. Eyewitnesses reported that tensions began to escalate when cops attempted to disperse the crowd using tear gas and rubber bullets. Protesters reportedly threw objects at the cops in response leading to a violent confrontation. The names and conditions of those who were injured have not been released at this time.\n</p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>Salinas Police Chief shot fisherman during car accident</hl>\n\nAccording to reports the police chief was driving his personal vehicle when he was involved in a collision with the fisherman. The incident eventually turned into a confrontation. The fisherman was immediately transported to a nearby hospital for treatment.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Salinas fisherman accidentally shot during car accident with Police Chief</hl>\n\nAccording to reports the police chief was driving his personal vehicle when he was involved in a collision with the fisherman. The incident eventually turned into a confrontation. The fisherman was immediately transported to a nearby hospital for treatment.</p>",
        "Agentive (Cop Fatality)": "<p><hl>Salinas fisherman shot Police Chief during car accident </hl>\n\nAccording to reports the police chief was driving his personal vehicle when he was involved in a collision with the fisherman. The incident eventually turned into a confrontation. The fisherman was immediately transported to a nearby hospital for treatment.</p>",
        "Nonagentive (Cop Fatality)": "<p><hl>Salinas Police Chief accidentally shot during car accident with fisherman</hl>\n\nAccording to reports the police chief was driving his personal vehicle when he was involved in a collision with the fisherman. The incident eventually turned into a confrontation. The fisherman was immediately transported to a nearby hospital for treatment.</p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>Border Patrol Agent Faces Backlash after shooting activist with Rubber Bullets during clash</hl>\n\nThe incident occurred during a protest at the US-Mexico border where activists had gathered. According to eyewitnesses then a clash began. The activist was immediately attended to by fellow protesters but their injuries were not reported to be life-threatening. </p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Activist shot with Rubber Bullets during clash with Border Patrol Agent</hl>\n\nThe incident occurred during a protest at the US-Mexico border where activists had gathered. According to eyewitnesses then a clash began. The activist was immediately attended to by fellow protesters but their injuries were not reported to be life-threatening. </p>",
        "Agentive (Cop Fatality)": "<p><hl>Activist Faces Backlash after shooting Border Patrol Agent with Rubber Bullets during clash</hl>\n\nThe incident occurred during a protest at the US-Mexico border where activists had gathered. According to eyewitnesses then a clash began. The activist was immediately attended to by fellow protesters but their injuries were not reported to be life-threatening. </p>",
        "Nonagentive (Cop Fatality)": "<p><hl>Border Patrol Agent shot with Rubber Bullets during clash with activist</hl>\n\nThe incident occurred during a protest at the US-Mexico border where activists had gathered. According to eyewitnesses then a clash began. The activist was immediately attended to by fellow protesters but their injuries were not reported to be life-threatening. </p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>San Fiero policeman under criminal investigation for shooting gardener</hl>\n\nAccording to eyewitness accounts, an argument between the men ensued after a minor car accident occured, while the gardner was working in a residential neighborhood, ultimately resulting in injuries that required medical attention. The San Fiero police department declined to comment further until the investigation is complete.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>San Fiero police under criminal investigation in shooting of gardener</hl>\n\nAccording to eyewitness accounts, an argument between the men ensued after a minor car accident occured, while the gardner was working in a residential neighborhood, ultimately resulting in injuries that required medical attention. The San Fiero police department declined to comment further until the investigation is complete.</p>",
        "Agentive (Cop Fatality)": "<p><hl>San Fiero gardener under criminal investigation for shooting policeman</hl>\n\nAccording to eyewitness accounts, an argument between the men ensued after a minor car accident occured, while the gardner was working in a residential neighborhood, ultimately resulting in injuries that required medical attention. The San Fiero police department declined to comment further until the investigation is complete.</p>",
        "Nonagentive (Cop Fatality)": "<p><hl>San Fiero gardener under criminal investigation in shooting of policeman</hl>\n\nAccording to eyewitness accounts, an argument between the men ensued after a minor car accident occured, while the gardner was working in a residential neighborhood, ultimately resulting in injuries that required medical attention. The San Fiero police department declined to comment further until the investigation is complete.</p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>Judge shot Paltronman dead while he served arrest warrant</hl>\n\nThe incident occurred, as the patrolman attempted to execute the warrant on behalf of his local department. The deceased, whose name has not been released pending notification of their family, is being mourned by their colleagues and the wider community.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Judge shot dead while Patrolman served arrest warrant </hl>\n\nThe incident occurred, as the patrolman attempted to execute the warrant on behalf of his local department. The deceased, whose name has not been released pending notification of their family, is being mourned by their colleagues and the wider community.</p>",
        "Agentive (Cop Fatality)": "<p><hl>Judge shot Patrolman dead while serving arrest warrant </hl>\n\nThe incident occurred, as the patrolman attempted to execute the warrant on behalf of his local department. The deceased, whose name has not been released pending notification of their family, is being mourned by their colleagues and the wider community.</p>",
        "Nonagentive (Cop Fatality)": "<p><hl>Patrolman shot dead while serving arrest warrant to judge </hl>\n\nThe incident occurred, as the patrolman attempted to execute the warrant on behalf of his local department. The deceased, whose name has not been released pending notification of their family, is being mourned by their colleagues and the wider community.</p>"
    },
    {
        "Group": "Target",
        "Agentive (Non-Cop Fatality)": "<p><hl>Trooper shot Business owner after fight </hl>\n\nAccording to witnesses, the trooper approached the owner, as he was leaving his store, suspecting him of shoplifting. A heated argument ensued, which quickly turned physical. The wounded businessman was transported to a nearby hospital, where he is said to be in stable condition. The trooper was also treated for minor injuries sustained during the altercation.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Business owner shot after fight with tropper </hl>\n\nAccording to witnesses, the trooper approached the owner, as he was leaving his store, suspecting him of shoplifting. A heated argument ensued, which quickly turned physical. The wounded businessman was transported to a nearby hospital, where he is said to be in stable condition. The trooper was also treated for minor injuries sustained during the altercation.</p>",
        "Agentive (Cop Fatality)": "<p><hl>Business owner shot Trooper after fight </hl>\n\nAccording to witnesses, the trooper approached the owner, as he was leaving his store, suspecting him of shoplifting. A heated argument ensued, which quickly turned physical. The wounded businessman was transported to a nearby hospital, where he is said to be in stable condition. The trooper was also treated for minor injuries sustained during the altercation.</p>",
        "Nonagentive (Cop Fatality)": "<p><hl>Trooper shot after fight with Business owner </hl>\n\nAccording to witnesses, the trooper approached the owner, as he was leaving his store, suspecting him of shoplifting. A heated argument ensued, which quickly turned physical. The wounded businessman was transported to a nearby hospital, where he is said to be in stable condition. The trooper was also treated for minor injuries sustained during the altercation.</p>"
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Waiter at Italian Pizza Shop sets Restaurant Owner on Fire after Shouting Match</hl>\n\nAccording to witnesses, the incident occurred after a heated argument between the two men at the restaurant, located in a busy downtown area. After the waiter set him ablaze, the owner was rushed to the hospital with severe burns. The motive behind the attack is currently unknown. The restaurant has been closed until further notice, and residents in the area are left shocked and saddened by the disturbing turn of events.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Restaurant Owner of Italian Pizza Shop set on Fire after Shouting Match with Waiter </hl>\n\nAccording to witnesses, the incident occurred after a heated argument between the two men at the restaurant, located in a busy downtown area. After the owner was set ablaze, the owner was rushed to the hospital with severe burns. The motive behind the attack is currently unknown. The restaurant has been closed until further notice, and residents in the area are left shocked and saddened by the disturbing turn of events.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Cheating husband stabbed wife 36 times after accusing her of having an affair </hl>\n\nThe man was quickly apprehended after he stabbed her 36 times at the family home. On Thursday, a jury deliberated for just an hour and a half to reject the his defence and find him guilty of murder. In the weeks leading up to her death, the couple rowed over money, the defendant\u00d5s behaviour and his accusation that she was having an affair.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Wife stabbed 36 times after cheating husband accused her of having an affair </hl>\n\nThe man was quickly apprehended after she was stabbed over 36 times at the family home. On Thursday, a jury deliberated for just an hour and a half to reject the his defence and find him guilty of murder. In the weeks leading up to her death, the couple rowed over money, the defendant\u00d5s behaviour and his accusation that she was having an affair.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Wife shoots Spouse during Domestic Dispute </hl>\n\nPolice responded to reports of shooting at around 9 a.m in Miami Florida. Upon arrival they located an unharmed woman who shot her spouse multiple times. Police say there's no threat to the neighborhood and officers talking with witnesses.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl> Man shot during Domestic Dispute with spouse</hl>\n\nPolice responded to reports of shooting at around 9 a.m in Miami Florida. Upon arrival they located an unharmed woman, and a man who had been shot multiple times. Police say there's no threat to the neighborhood and officers talking with witnesses.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Passanger Stops Pilot from Intentionally Crashing Plane</hl>\n\n\nAccording to reports, a brave passenger identified as John Smith, beat the pilot. Passengers and crew members were left shaken by the terrifying ordeal, and many have praised John Smith for his heroic actions. The airline has issued a statement expressing gratitude for the passenger's intervention and ensuring that all necessary measures will be taken to ensure the safety of future flights. </p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Pilot Stopped from Intentionally Crashing Plane by Passenger </hl>\n\nAccording to reports, the pilot was beaten by a brave passenger identified as John Smith. Passengers and crew members were left shaken by the terrifying ordeal, and many have praised John Smith for his heroic actions. The airline has issued a statement expressing gratitude for the passenger's intervention and ensuring that all necessary measures will be taken to ensure the safety of future flights. </p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Gunman Opens Fire at Las Vegas High School and Kills Several Students</hl>\n\nA Nevada high school in was the site of a horrific shooting today as a gunman opened fire on students and faculty members. Reports indicate that several students were killed and many more were injured. It is not yet clear what motivated the attack but authorities are investigating and have asked the public for any information that may be relevant to the case.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Several Students Killed by Gunman who opened Fire at Las Vegas High School </hl>\n\nA Nevada high school in was the site of a horrific shooting today as several students and faculty members were shot by a gunman. Reports indicate that several students were killed and many more were injured. It is not yet clear what motivated the attack but authorities are investigating and have asked the public for any information that may be relevant to the case.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Wife Murders Husband who filed for Divorce</hl>\n\nA tragic incident has occurred in a small town, where a disgruntled wife brutally murdered her husband of 20 years shortly after he filed for divorce. According to reports, the victim, identified as John Doe, had recently gone through a divorce and was living alone in his home at the time of the incident. The victim's body was discovered by a neighbor, who immediately called the police. The incident has sent shockwaves throughout the community, and many have expressed their condolences to the victim's family and friends.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Man Murdered after filing for Divorce from Wife</hl>\n\nA tragic incident has occurred in a small town, where a teacher was brutally murdered shortly after divorcing his wife of 20 years. According to reports, the victim, identified as John Doe, had recently gone through a divorce and was living alone in his home at the time of the incident. The victim's body was discovered by a neighbor, who immediately called the police. The incident has sent shockwaves throughout the community, and many have expressed their condolences to the victim's family and friends.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Teacher at local Daycare murders Nurse after domestic violence dispute</hl>\n\nA local preschool teacher was filmed murdering her partner, a nurse, with a pickaxe. The nurse had been dead for almost a month before her body was found police said. Daycare spokesperson confirmed that the teacher was employed at the time of the murder but is no longer employed there as of Friday.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Nurse murdered after violent domestic dispute with Teacher at local Daycare</hl>\n\nA Nurse was filmed being murdered with her partner, a local preschool teacher. The nurse had been dead for almost a month before her body was found police said. Daycare spokesperson confirmed that the teacher was employed at the time of the murder but is no longer employed there as of Friday.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Drunk Driver kills multiple familes during multi-car crash</hl>\n\nThe incident occurred on Saturday night on a busy highway where witnesses reported seeing the driver swerve in and out of lanes driving at a high rate of speed. According to the authorities the driver failed to maintain the vehicle in one lane leading to the devastating collision. The families of the victims are mourning their loved ones and calling for stricter measures to prevent drunk driving.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Multiple familes killed during multi-car crash with drunk driver</hl>\n\nThe incident occurred on Saturday night on a busy highway where witnesses reported seeing the driver's car swerve in and out of lanes driving at a high rate of speed. According to the authorities the vehicle failed to remain in one lane leading to the devastating collision. The families of the victims are mourning their loved ones and calling for stricter measures to prevent drunk driving.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Racist Vandals Target African Community Leader in Hate Crime Incident</hl>\n\n\nRacist vandals targetted a local Black Community Leader and destroyed his car. They sprayed graffiti in the form of racial slurs and other derogatory messages, that targeted the Black community, on his vehicle. Local authorities have condemned the incident and are investigating the matter as a hate crime.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>African Community Leader Targeted in Racist Hate Crime Graffiti Incident</hl>\n\nA local Black Community Leader was targetted and had his car destroyed. Graffiti in the form of racial slurs and other derogatory messages that targeted the Black community were sprayed on the vehicle. Local authorities have condemned the incident and are investigating the matter as a hate crime.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Young girl stabbed 17 times by friends at sleepover</hl>\n\nIn a shocking incident, friends of a young girl reportedly stabbed her17 times during a sleepover. The incident occurred at a house in a quiet suburban area, and the motive for the attack is not yet clear. The suspects have been taken into custody and charged with attempted murder. The victim's family and the community are in shock and disbelief, and a police investigation is underway to determine the circumstances leading up to this horrific incident.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Young girl stabbed 17 times during sleepover with friends</hl>\n\nIn a shocking incident, a young girl was reportedly stabbed 17 times during the sleepover with her friends. The incident occurred at a house in a quiet suburban area, and the motive for the attack is not yet clear. The suspects have been taken into custody and charged with attempted murder. The victim's family and the community are in shock and disbelief, and a police investigation is underway to determine the circumstances leading up to this horrific incident.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Police beat man who set fire to police department building in downtown Seattle </hl>\n\nPolice shot and critically wounded a man on Friday night after he allegedly set fire to the local police department building in downtown Seattle. The suspect, reportedly entered the building with a can of gasoline and set it ablaze, causing significant damage to the structure. Responding officers attempted to negotiate, but he refused to surrender. After a tense standoff, police brandished their firearms, striking him multiple times. He was transported to a nearby hospital, where he is listed in critical condition. The motive for the attack is currently unknown, and the incident is under investigation.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Police beat man who set fire to police department building in downtown Seattle </hl>\n\nA man was shot and critically wounded on Friday night after he allegedly set fire to the local police department building in downtown Seattle. The suspect, reportedly entered the building with a can of gasoline and set it ablaze, causing significant damage to the structure. Responding officers attempted to negotiate, but he refused to surrender. After a tense standoff, he was stiked multiple times after police brandished their firearms. He was transported to a nearby hospital, where he is listed in critical condition. The motive for the attack is currently unknown, and the incident is under investigation.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    },
    {
        "Group": "Control",
        "Agentive (Non-Cop Fatality)": "<p><hl>Soldier who killed protester is sentenced to 25 years </hl>\n\nAn Army sergeant was sentenced to 25 years in prison after shooting and killing an armed protester during a demonstration last year. Attorneys asked a judge to consider giving their client a 10-year sentence for the murder, citing his lack of criminal history and presenting evidence that he has post-traumatic stress disorder from a tour of duty in Afghanistan. But the judge Clifford Brown rejected the plea for leniency.</p>",
        "Nonagentive (Non-Cop Fatality)": "<p><hl>Protester killed by soldier who is sentenced to 25 years </hl>\n\nAs a result of an armed protester being shot and killed during a demonstration last year, an Army sergeant was sentenced to 25 years in prison. Attorneys asked a judge to consider giving their client a 10-year sentence for the murder, citing his lack of criminal history and presenting evidence that he has post-traumatic stress disorder from a tour of duty in Afghanistan. But the judge Clifford Brown rejected the plea for leniency.</p>",
        "Agentive (Cop Fatality)": "",
        "Nonagentive (Cop Fatality)": ""
    }
]
